name: first workflow

on:
  repository_dispatch:
    types: [test] # Triggered by external repository_dispatch event
  push:
    branches:
      - "main" # Triggered on push to the main branch
  pull_request:
    branches:
      - "feature" # Triggered for pull requests targeting the "feature" branch
    types: [opened, closed]

jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    
    steps:
      - name: List files before checkout
        run: ls
        shell: bash
      
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List files after checkout
        run: ls
        shell: bash
