name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  first-workflow-job:
    name: first job 
    runs-on: ubuntu-latest
    steps:
    - name: before checkout
      run: ls
      
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: after checkout 
      run: ls
      shell: bash
